services:
  db:
    image: postgres:17.6
    container_name: fastapi-db-pg
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_postgresql:/var/lib/postgresql
      - db_postgresql_data:/var/lib/postgresql/data
    networks:
      - fastapi

  redis:
    container_name: fastapi-db-redis
    image: redis:7.2.4
    command: redis-server --requirepass dY5MRW2^!jxHX
    ports:
      - 6379:6379
    restart: always
    networks:
      - fastapi

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: fastapi-db-kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@fastapi-db-kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fastapi-db-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - '9092:9092'
      - '29093:29093'
    networks:
      - fastapi
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fastapi-kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: fastapi-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: fastapi-db-kafka:9092
    networks:
      - fastapi

networks:
  fastapi:
    driver: bridge

volumes:
  db_postgresql:
  db_postgresql_data:
  kafka_data: